name: deploy

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set git user information
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
        env:
          USER_NAME: Kisstar
          USER_EMAIL: dwh.chn@foxmail.com

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Builds the app for production
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Deploy with gh-pages for GitHub
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: kisstar/knives
          branch: gh-pages
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
